services:
  - type: web
    name: twiller-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONOGDB_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PORT
        value: 10000
